name: Apps_workflow

on:
  push:
    paths:
      - 'Apps/**' # 监视 Apps 文件夹及其子文件夹下的内容
  pull_request:
    paths:
      - 'Apps/**' # 监视 Apps 文件夹及其子文件夹下的内容
  workflow_dispatch:

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate JSON
      run: |
        python .github/scripts/Apps.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: json-artifact
        path: ${{ github.workspace }}

    - name: Push to Apps Repository
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Update generated image JSON file"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
